# Index dependencies
quarkus.index-dependency.rimfrost-adapter-arbetsgivare.group-id=se.fk.rimfrost.adapter.arbetsgivare
quarkus.index-dependency.rimfrost-adapter-arbetsgivare.artifact-id=rimfrost-adapter-arbetsgivare
quarkus.index-dependency.rimfrost-adapter-referensdata.group-id=se.fk.rimfrost.adapter.referensdata
quarkus.index-dependency.rimfrost-adapter-referensdata.artifact-id=rimfrost-adapter-referensdata
quarkus.index-dependency.rimfrost-adapter-folkbokford.group-id=se.fk.rimfrost.adapter.folkbokford
quarkus.index-dependency.rimfrost-adapter-folkbokford.artifact-id=rimfrost-adapter-folkbokford
quarkus.index-dependency.rimfrost-framework-regel-manuell.group-id=se.fk.rimfrost.framework.regel.manuell
quarkus.index-dependency.rimfrost-framework-regel-manuell.artifact-id=rimfrost-framework-regel-manuell

kafka.source=RegelBekraftaBeslut
kafka.subtopic=bekraftabeslut

# Container image configuration
quarkus.container-image.name=rimfrost-regel-bekraftabeslut

#Incoming
mp.messaging.incoming.regel-requests.topic=bekraftabeslut-requests
mp.messaging.incoming.operativt-uppgiftslager-status-notification.topic=operativt-uppgiftslager-status-notification.bekraftabeslut

#Outgoing
mp.messaging.outgoing.regel-responses.topic=bekraftabeslut-responses

# Persistence
quarkus.flyway.default-schema=regel_bekraftabeslut
regel.persistence.table-prefix=bekraftabeslut

%prod.quarkus.datasource.username=${DB_USERNAME}
%prod.quarkus.datasource.password=${DB_PASSWORD}
%prod.quarkus.datasource.jdbc.url=${DB_URL}

# REST setup
arbetsgivare.api.base-url=http://rimfrost-k8s-arbetsgivare:8080
folkbokford.api.base-url=http://rimfrost-k8s-folkbokford:8080
referensdata.api.base-url=http://rimfrost-k8s-referensdata:8080
oul.api.base-url=http://rimfrost-operativt-uppgiftslager:8080
